
const PracticeConstant = {
    CHANGE_PRACTICE_TYPE: '[PRACTICE] CHANGE_PRACTICE_TYPE',
    START_PRACTICE_ONE_WORD: '[PRACTICE] START_PRACTICE_ONE_WORD',
    START_PRACTICE_SECTION: '[PRACTICE] START_PRACTICE_SECTION',
    SUBMIT_ANSWER: '[PRACTICE] SUBMIT_ANSWER',
    SUBMIT_ANSWER_SUCCESS: '[PRACTICE] SUBMIT_ANSWER_SUCCESS',
    SUBMIT_ANSWER_FAILED: '[PRACTICE] SUBMIT_ANSWER_FAILED',
    CHANGE_PRACTICE_TYPE: '[PRACTICE] CHANGE_PRACTICE_TYPE',
    PRACTICE_TYPE_ENG_TO_VIE: 'PRACTICE_TYPE_ENG_TO_VIE',
    PRACTICE_TYPE_VIE_TO_ENG: 'PRACTICE_TYPE_VIE_TO_ENG',
    ANSWER_STATUS_NOT_ANSWER: 'ANSWER_STATUS_NOT_ANSWER',
    ANSWER_STATUS_CORRECT: 'ANSWER_STATUS_CORRECT',
    ANSWER_STATUS_INCORRECT: 'ANSWER_STATUS_INCORRECT',
};
export default PracticeConstant;