
const WordConstant = {
    GET_ALL_WORDS: '[VOCAB] GET_ALL_WORDS',
    GET_VOCAB_LIST_SUCCESS: '[VOCAB] GET_VOCAB_LIST_SUCCESS',
    GET_VOCAB_LIST_FAILED: '[VOCAB] GET_VOCAB_LIST_FAILED',
    UPDATE_VOCAB: '[VOCAB] UPDATE_VOCAB',
    UPDATE_VOCAB_SUCCESS: '[VOCAB] UPDATE_VOCAB_SUCCESS',
    UPDATE_VOCAB_FAILED: '[VOCAB] UPDATE_VOCAB_FAILED',
    DELETE_VOCAB: '[VOCAB] DELETE_VOCAB',
    DELETE_VOCAB_SUCCESS: '[VOCAB] DELETE_VOCAB_SUCCESS',
    DELETE_VOCAB_FAILED: '[VOCAB] DELETE_VOCAB_FAILED',
    CREATE_VOCAB: '[VOCAB] CREATE_VOCAB',
    CREATE_VOCAB_SUCCESS: '[VOCAB] CREATE_VOCAB_SUCCESS',
    CREATE_VOCAB_FAILED: '[VOCAB] CREATE_VOCAB_FAILED',
    SAVE_CURRENT_PAGE: '[VOCAB] SAVE_CURRENT_PAGE',
    SET_IS_OPEN_EDIT_MODAL: '[VOCAB] SET_IS_OPEN_EDIT_MODAL',
    SET_IS_OPEN_DELETE_MODAL: '[VOCAB] SET_IS_OPEN_DELETE_MODAL',
    SET_IS_OPEN_ADD_MODAL: '[VOCAB] SET_IS_OPEN_ADD_MODAL',
    SET_UPDATE_VOCAB_ERROR_MESSAGE: '[VOCAB] SET_UPDATE_VOCAB_ERROR_MESSAGE',
    SET_DELETE_VOCAB_ERROR_MESSAGE: '[VOCAB] SET_DELETE_VOCAB_ERROR_MESSAGE',
    SET_CREATE_VOCAB_ERROR_MESSAGE: '[VOCAB] SET_CREATE_VOCAB_ERROR_MESSAGE',
};
export default WordConstant;